// 常量相关
export const accessToken = 'ACCESSTOKEN'
export const searchHistory = 'SEARCHHISTORY'// 搜索历史
export const experience = 'EXPERIENCE' // 体验馆
export const comment = 'COMMENT' // comment
export const createOrderFrom = 'CREATEORDERFROM'
export const goodsInfo = 'GOODSINFO' // 创建订单时商品详情需传的goodsItems
export const orderInfo = 'ORDERINFO' // 创建订单时商品的配送和优惠券及发票相关信息
export const invoiceInfo = 'INVOICEINFO' // 发票信息
export const goodsListData = 'GOODSLISTDATA'
export const cartGoods = 'CARTGOODS'// 在页面跳转之前购物车的数据（分页原因）
export const couponByGoods = 'COUPONBYGOODS' // 创建订单选择相关优惠券
export const logistics = 'LOGISTICS' // 物流订单
export const aftersale = 'AFTERSALE' // 售后
export const orderSn = 'ORDERSN' // 申请开票需要的订单号
export const searchorder = 'SEARCHORDER' // 订单搜索
export const retrunLogistics = 'RETRUNLOGISTICS' // 退货物流
export const immedPaymentMony = 'IMMEDPAYMENTMONY' // 支付金额
export const activityCategory = 'ACTIVITYCATEGORY' // 品类秒杀查看详情
export const fromRoute = 'FROMROUTE' // 编辑收入地址的地址来自哪里
